---
language: python
services: docker

env:
  global:
    - ROLE_NAME: sl
  matrix:
    - MOLECULE_DISTRO: centos7
    - MOLECULE_DISTRO: centos6
    - MOLECULE_DISTRO: centos5

install:
  # Install test dependencies.
  - pip install molecule docker

before_script:
  # Use actual Ansible Galaxy role name for the project directory.
  - cd ../
  - mv Ansible-role-$ROLE_NAME hemanth22.$ROLE_NAME
  - cd hemanth22.$ROLE_NAME

script:
  # Run tests.
  - molecule test

after_failure:
    #- set -x
  - wget -O createIssue.sh https://gist.githubusercontent.com/hemanth22/3b5d1dae822e95b3b7b30912e7b54a62/raw/fd6405f5e9b9804a468ca96e9178cf1d354ff71c/createIssue.sh
  - chmod 777 createIssue.sh
  - ./createIssue.sh

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
