---
# tasks file for sl
- name: Ensure EPEL is installed
  yum: name=epel-release state=present
  when: ansible_distribution == 'CentOS' or
        ansible_distribution == 'Red Hat Enterprise Linux' or
        ansible_distribution == 'RedHat'
#  when: ansible_os_family == 'RedHat'
  notify:
  - Install SL
