---
# handlers file for sl
- name: Install SL
  yum: name=sl state=present
  when: ansible_distribution == 'CentOS' or
        ansible_distribution == 'Red Hat Enterprise Linux' or
        ansible_distribution == 'RedHat'
  tags:
    - skip_ansible_lint
